version: '3.8'

services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "python bot.py"

  parser:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python models.py && python main_parser.py"
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "tesmanian"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "example"
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  database-data:
